# Generated by Django 2.0 on 2018-12-24 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('PriKey', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Heading', models.CharField(max_length=100)),
                ('DateOfPost', models.DateField(default=datetime.date(2018, 12, 24))),
                ('Content', models.TextField()),
            ],
        ),
    ]
